# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=50, verbose_name='口令')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('img', models.ImageField(upload_to='user/images', verbose_name='头像')),
            ],
        ),
    ]
